# Generated by Django 5.2.5 on 2025-10-04 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedsapp', '0002_alter_feedback_options_alter_hallbooking_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Superserver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
