# Generated by Django 5.2.7 on 2025-10-17 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedsapp', '0003_superserver'),
    ]

    operations = [
        migrations.AddField(
            model_name='hallbooking',
            name='food_items',
            field=models.TextField(blank=True, null=True),
        ),
    ]
